In [2]:
import numpy as np

x= np.array([[1,3],[2,4]])
y= np.array([[2,4],[3,5]])

print(x)
print(y)
x.ndim

[[1 3]
 [2 4]]
[[2 4]
 [3 5]]


2

In [3]:
def naive_add(x,y):
    assert len(x.shape)==2
    assert x.shape==y.shape
    
    x= x.copy()
    
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i][j] += y[i][j]
            
    return x

naive_add(x,y)
    
    
    

array([[3, 7],
       [5, 9]])

In [5]:
def naive_relu(x):
    assert len(x.shape)==2
    x= x.copy()  
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i][j] = max(x[i][j],0)
            
    return x

z=  np.array([[-2,-4],[3,5]])
naive_relu(z)
    

array([[0, 0],
       [3, 5]])

In [7]:
def naive_add_matrix_and_vector(x,y):
    assert len(x.shape)==2
    assert len(y.shape)==1
    assert x.shape[1] == y.shape[0]
    
    x = x.copy()
    
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i][j] += y[j]
            
    return x
    

In [9]:
x= np.array([[1,3],[2,4]])
y= np.array([1,2])

print('x :\n',x)
print('y :\n',y)
print('------------------')
print(naive_add_matrix_and_vector(x,y))

x :
 [[1 3]
 [2 4]]
y :
 [1 2]
------------------
[[2 5]
 [3 6]]


In [14]:
def naive_vector_dot(x,y):
    assert len(x.shape)==1
    assert len(y.shape)==1,"dimension is not 1"
    assert x.shape[0] == y.shape[0]
    
    z=0
    
    for i in range(x.shape[0]):
        z += x[i]*y[i]
            
            
    return z


    

In [26]:
x= np.array([10,20])
y= np.array([1,2])
naive_vector_dot(x,y)



50

In [24]:
def naive_matrix_vector_dot(x,y):
    assert len(x.shape)==2
    assert len(y.shape)==1
    assert x.shape[1] == y.shape[0]
    
    z=np.zeros(x.shape[0])
    
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i]+= x[i][j]*y[j]
            
            
    return z


    

In [29]:
x= np.array([[1,3],[2,4]])
y= np.array([1,2])
print('x :\n',x)
print('y :\n',y)
print('------------------')
print(naive_matrix_vector_dot(x,y))


x :
 [[1 3]
 [2 4]]
y :
 [1 2]
------------------
[ 7. 10.]
